name: Documentation Publish

on:
  workflow_run:
    workflows: ["Documentation Build"]
    types:
      - completed
  workflow_dispatch:
      inputs:
        id_num:
          description: 'worflow id'
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: docbuild.yml
          #run_id: ${{ inputs.id_num }}
          run_id: ${{ github.event.workflow_run.id }}

      - name: Unzip html archive
        working-directory: docs
        run: |
          OUTDIR=$(awk 'NR==1 { if ($3 ~ /^(latest|PR-[0-9]+)$/) print $3 }' monitor_*.txt)
          echo "OUTDIR=$OUTDIR" >> "$GITHUB_ENV"
          unzip legacy-ncs*.zip -d $OUTDIR

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.NCSDOC_STORAGE_CREDS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: 2.65.0
          inlineScript: |
            az storage blob upload-batch --destination \$web --account-name ncsdoc --destination-path $OUTDIR --source docs/$OUTDIR

      - name: Upload Zoomin documentation
        run: |
          for file in docs/monitor*.txt; do
            if ! grep -q main ${file}; then
              echo "Not targeting main, skipping Zoomin upload"
              exit 0
            fi
          done
          # trust server
          mkdir -p ~/.ssh
          ssh-keyscan upload-v1.zoominsoftware.io >> ~/.ssh/known_hosts
          # prepare key
          echo "${{ secrets.NCS_ZOOMIN_KEY }}" | base64 -d > zoomin_key
          chmod 600 zoomin_key
          # upload files
          for file in docs/*-apis-*.zip; do
            sftp -v -i zoomin_key nordic@upload-v1.zoominsoftware.io <<EOF
            cd docs-be.nordicsemi.com/doxygen/incoming
            put ${file}
            cd ../../../nordic-be-dev.zoominsoftware.io/doxygen/incoming
            put ${file}
            quit
          EOF
          done
          for file in docs/ncs-*.zip; do
            sftp -v -i zoomin_key nordic@upload-v1.zoominsoftware.io <<EOF
            cd docs-be.nordicsemi.com/sphinx-html/incoming
            put ${file}
            cd ../../../nordic-be-dev.zoominsoftware.io/sphinx-html/incoming
            put ${file}
            quit
          EOF
          done

      - name: Add preview URL comment for PRs
        uses: carlescufi/action-doc-url@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          urlroot: "https://ncsdoc.z6.web.core.windows.net/"
          pr-prefix: "PR-"
          pr-file: docs/pr.txt
