name: Documentation Remove

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Try removal of PR-docs
        env:
          AZCOPY_CONCURRENCY_VALUE: 3000
        run: |
          azcopy rm "https://ncsdoc.blob.core.windows.net/\$web/PR-${{ github.event.number }}?${{ secrets.NCSDOC_SAS }}" --recursive=true || true

