name: Documentation Remove

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Try removal of PR-docs
        run: |
          azcopy rm "https://ncsdoc.blob.core.windows.net/\$web/PR-${{ github.event.number }}?${{ secrets.NCSDOC_SAS}}" --recursive=true || true

