name: Reapply CI-trusted-author label

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  remove_label:
    if: ${{ contains(github.event.*.labels.*.name, 'CI-trusted-author') }}
    runs-on: ubuntu-latest
    name: Remove label
    steps:
      - name: Remove CI-trusted-author label
        run: gh pr edit ${{ github.event.pull_request.number }} --remove-label "CI-trusted-author"

 #     - name: Add CI-trusted-author label
 #       run: gh pr edit ${{ github.event.pull_request.number }} --add-label "CI-trusted-author"



