name: Remove CI requested label

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  remove_label:
    runs-on: ubuntu-latest
    name: Remove label
    steps:
      - name: Remove CI-requested label
        run: gh pr edit ${{ github.event.pull_request.number }} --remove-label "CI-Requested"

