name: SonarCloud
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    paths:
      - '**/*.c'
      - '**/*.h'
 
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-22.04
    container: ghcr.io/nrfconnect/sdk-nrf-toolchain:v2.9.0
    defaults:
      run:
        # Bash shell is needed to set toolchain related environment variables in docker container
        # It is a workaround for GitHub Actions limitation https://github.com/actions/runner/issues/1964
        shell: bash

    steps:
      - uses: nrfconnect/action-checkout-west-update@main
        if: github.event_name == 'pull_request'
        with:
          git-ref: ${{ github.event.pull_request.head.sha }}
          git-fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          path: ncs/nrf
        
      - uses: nrfconnect/action-checkout-west-update@main
        if: github.event_name != 'pull_request'
        with:
          git-fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          path: ncs/nrf

      - name: Install dependencies
        run: |
            apt-get update
            apt-get install -y curl unzip ruby gcc-multilib make

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v4

      - name: Build and test
        working-directory: ncs/nrf
        run: |
          build-wrapper-linux-x86-64 --out-dir build_wrapper_output ../zephyr/scripts/twister \
            --ninja --integration \
            --quarantine-list scripts/quarantine.yaml --quarantine-list scripts/quarantine_integration.yaml \
            -T applications/asset_tracker_v2

      - name: Upload Build Wrapper Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build_wrapper_output
          path: build_wrapper_output
          
