name: Zephyr upmerge

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          path: ncs/nrf
          fetch-depth: 0
      - name: Install packages
        run: |
          sudo apt update
          sudo apt-get install -y ninja-build mscgen plantuml libclang1-9 libclang-cpp9

      - name: Install base dependencies
        working-directory: ncs
        run: |
          sudo pip3 install -U setuptools wheel pip
          pip3 install -r nrf/scripts/requirements-base.txt
          pip3 install -r nrf/scripts/requirements-extra.txt

      - name: West init and update
        working-directory: ncs
        run: |
          west init -l nrf
          west update
          west ncs-upmerger
